version: '3'

services:

  webdb:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_DATABASE=auth
      - MYSQL_USER=root
    volumes:
      - ./auth/data/:/var/lib/mysql/
    ports:
      - "3308:3306"
    networks:
      - webapp-network

  webapp:
    build:
      context: .
    ports:
      - '8082:8000'
    environment:
      - VIRTUAL_HOST=localhost
    depends_on:
      - webdb
    volumes:
      - './auth:/var/www/html'
    networks:
      - webapp-network

  productservice:
    build:
      context: .
      dockerfile: DockerNodefile
    ports:
      - '8083:8000'
    environment:
      - VIRTUAL_HOST=localhost
    volumes:
      - './productservice:/var/www/html'
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
